---

name: Build and deploy to Firebase
on:
  push:
    branch:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install hugo
        run: |
          wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.71.1/hugo_0.71.1_Linux-64bit.tar.gz
          tar -C /tmp -xf /tmp/hugo.tar.gz
          sudo mv /tmp/hugo /usr/bin/

      - name: Checkout
        uses: actions/checkout@master

      - name: Build site
        run: hugo

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
